DROP TABLE IF EXISTS DOMICILIOS;
CREATE TABLE DOMICILIOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(200),
NUMERO INT,
LOCALIDAD VARCHAR(100),
PROVINCIA VARCHAR(100));

DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(100),
DNI INT,
FECHA DATE,
DOMICILIO_ID INT);

