DROP TABLE IF EXISTS DOMICILIOS;
CREATE TABLE DOMICILIOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(200),
NUMERO INT,
LOCALIDAD VARCHAR(100),
PROVINCIA VARCHAR(100));

DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(100),
DNI INT,
FECHA DATE,
DOMICILIO_ID INT);

-- creo algunos pacientes para realizar test
INSERT INTO DOMICILIOS (CALLE, NUMERO, LOCALIDAD, PROVINCIA) VALUES ('Calle 1', 25, 'Salta', 'Salta');
INSERT INTO DOMICILIOS (CALLE, NUMERO, LOCALIDAD, PROVINCIA) VALUES ('Calle 2', 45, 'Capital Federal', 'Buenos Aires');

INSERT INTO PACIENTES (NOMBRE, DNI, FECHA, DOMICILIO_ID) VALUES ('Juan', 121222, '2022-5-12', 1);
INSERT INTO PACIENTES (NOMBRE, DNI, FECHA, DOMICILIO_ID) VALUES ('Roberto', 325345, '2022-5-12', 2);